version: "3"

networks:
    nginx_default:
        external: true

services:
    server:
        restart: always
        image: node
        user: node
        working_dir: /home/node
        command: npm start
        ports:
            - 8081:8081
        tty: true
        stdin_open: true
        volumes:
            - .:/home/node
        networks:
            - nginx_default

    npm:
        image: node
        user: node
        working_dir: /home/node
        entrypoint: npm
        tty: true
        stdin_open: true
        volumes:
            - .:/home/node

    node:
        image: node
        user: node
        working_dir: /home/node
        entrypoint: node
        tty: true
        stdin_open: true
        volumes:
            - .:/home/node
